repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
      exclude: ^\.lintr$
    - id: end-of-file-fixer
      exclude: ^\.lintr$

- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.3.9013
  hooks:
    - id: lintr
      exclude: ^\.lintr$
