# .pre-commit-config.yaml
minimum_pre_commit_version: "3.0.0"
default_stages: [pre-commit]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(renv/|\.lintr$)
      - id: end-of-file-fixer
        exclude: ^(renv/|\.lintr$)
