name: lintr

on:
  push:
    branches: [main, master]
  pull_request:

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LINTR_ERROR_ON_LINT: true
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Restore renv and lint
        run: |
          Rscript -e "Sys.setenv(RENV_CONFIG_REQUIRE_PROMPT='FALSE'); renv::restore(prompt = FALSE)"
          Rscript -e "lintr::lint_package()"
