name: lintr
on:
  push:
    branches: [main, master]
  pull_request:
jobs:
  lintr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install lintr
        run: Rscript -e 'install.packages("lintr")'
      - name: Run lintr
        run: Rscript -e 'lintr::lint_package()'
