name: pkgdown
on:
  push:
    branches: [main]
jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions: { contents: write, pages: write, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with: { extra-packages: any::pkgdown, needs: website }
      - name: Build site
        run: Rscript -e "pkgdown::build_site_github_pages(new_process=FALSE, install=TRUE)"
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
