name: R CMD Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: r-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 30
    continue-on-error: ${{ matrix.config.allow-failure || false }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # Simplified for GitHub-only distribution (not CRAN)
          # Test on main platforms with R release only
          # macOS has known gdtools compilation issues (libintl linking) - allowed to fail
          - {os: macos-latest,   r: 'release', allow-failure: true}
          - {os: ubuntu-latest,  r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          # Temporarily relaxed checking until issue #9 is resolved
          error-on: '"error"'
          args: 'c("--no-manual", "--as-cran", "--no-examples")'
