name: R CMD Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 30
    concurrency:
      group: r-check-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        config:
          # Simplified for GitHub-only distribution (not CRAN)
          # Test on main platforms with R release only
          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install system dependencies for gdtools
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config cairo pango libpng jpeg giflib fontconfig gettext
          brew link gettext --force

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
