---
name: R CMD Check

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  r-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends \
              libcurl4-openssl-dev \
              libssl-dev \
              libxml2-dev \
              zlib1g-dev

      - name: Check package
        run: R CMD check --no-manual --no-build-vignettes --as-cran .
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-rcheck
          path: tidycreel.Rcheck
