name: R-CMD-check

on: [push, pull_request]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['release']
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gettext
          brew install harfbuzz fribidi
          brew link --force gettext
      - name: Configure R build environment (macOS)
        if: runner.os == 'macOS'
        run: |
          # Create R Makevars with proper library paths
          mkdir -p ~/.R

          # Set paths for both Intel and Apple Silicon Macs
          if [[ -d "/opt/homebrew" ]]; then
            # Apple Silicon Mac
            echo 'LDFLAGS=-L/opt/homebrew/lib -L/opt/homebrew/opt/gettext/lib' > ~/.R/Makevars
            echo 'CPPFLAGS=-I/opt/homebrew/include -I/opt/homebrew/opt/gettext/include' >> ~/.R/Makevars
            echo 'PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/opt/gettext/lib/pkgconfig' >> ~/.R/Makevars
            echo 'LIBRARY_PATH=/opt/homebrew/lib:/opt/homebrew/opt/gettext/lib' >> ~/.R/Makevars
            echo 'LDFLAGS=-L/opt/homebrew/lib -L/opt/homebrew/opt/gettext/lib' >> $GITHUB_ENV
            echo 'CPPFLAGS=-I/opt/homebrew/include -I/opt/homebrew/opt/gettext/include' >> $GITHUB_ENV
            echo 'PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/opt/gettext/lib/pkgconfig' >> $GITHUB_ENV
            echo 'LIBRARY_PATH=/opt/homebrew/lib:/opt/homebrew/opt/gettext/lib' >> $GITHUB_ENV
          else
            # Intel Mac
            echo 'LDFLAGS=-L/usr/local/lib -L/usr/local/opt/gettext/lib' > ~/.R/Makevars
            echo 'CPPFLAGS=-I/usr/local/include -I/usr/local/opt/gettext/include' >> ~/.R/Makevars
            echo 'PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/gettext/lib/pkgconfig' >> ~/.R/Makevars
            echo 'LIBRARY_PATH=/usr/local/lib:/usr/local/opt/gettext/lib' >> ~/.R/Makevars
            echo 'LDFLAGS=-L/usr/local/lib -L/usr/local/opt/gettext/lib' >> $GITHUB_ENV
            echo 'CPPFLAGS=-I/usr/local/include -I/usr/local/opt/gettext/include' >> $GITHUB_ENV
            echo 'PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/gettext/lib/pkgconfig' >> $GITHUB_ENV
            echo 'LIBRARY_PATH=/usr/local/lib:/usr/local/opt/gettext/lib' >> $GITHUB_ENV
          fi
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::testthat
            any::lintr
            any::styler
          needs: check
      - name: Check
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          R_DEFAULT_INTERNET_TIMEOUT: 20
          LC_ALL: ${{ runner.os != 'Windows' && 'C.UTF-8' || '' }}
        run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--as-cran'), error_on='warning', check_dir='check')"
      - name: Upload check results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: r-cmd-check-results
          path: check
